name: Create and publish a Docker image

on:
  push:
    branches: ["martine"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gateway-proxy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image - skylake
        uses: whoan/docker-build-with-cache-action@v6
        with:
          username: MartineBot
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          image_name: gateway-proxy
          build_extra_args: '{"--build-arg": "TARGET_CPU=skylake"}'
          tags: "latest,${{ github.sha }},skylake"

      - name: Build and push Docker image - znver2
        uses: whoan/docker-build-with-cache-action@v6
        with:
          username: MartineBot
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          image_name: gateway-proxy
          build_extra_args: '{"--build-arg": "TARGET_CPU=znver2"}'
          tags: "latest,${{ github.sha }},znver2"
